// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbFirstExample.Models;

public partial class WorkType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<WorkItem> WorkItem { get; set; } = new List<WorkItem>();
}