// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbFirstExample.Models;

public partial class WorkItem
{
    public int Id { get; set; }

    public string Description { get; set; }

    public int WorkTypeId { get; set; }

    public virtual WorkType WorkType { get; set; }
}